### ISSUE TITLE
Bug: Deserialization doesn't support multiple LP types

### ISSUE THREAD

**Issue by nmcglo** [gonsie/RIO#13]
https://github.com/gonsie/RIO/blob/94c1521f536f0b8e8824e856d49bc0b8fdb34bdc/io-mpi.c#L210

Hardcoded to deserialize using the deserialize function for the 0th LP type. 

Compare with the serialize method in the same file:

https://github.com/gonsie/RIO/blob/94c1521f536f0b8e8824e856d49bc0b8fdb34bdc/io-mpi.c#L354

**Comment by gonsie** [comment]
good catch!
